name: Update idx daily data

on:
  schedule:
      - cron: '0 11 * * 1-5' # run at every weekday at 18:00 GMT+7
  workflow_dispatch:

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r base_requirements.txt
          pip install -r idx_requirements.txt

      - name: execute idx_scrape_data.py script
        env:
            SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python idx_daily_data_scrape.py
          
