name: Update US financials_annual with USYFDataUpdater

on:
  schedule:
      - cron: '0 1 * * 6' # run at 10th day of every saturday at 0:800 GMT+7
  workflow_dispatch:

jobs:
    trigger_workflow:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo content
              uses: actions/checkout@v2 # checkout the repository content to github runner

            - name: setup python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.9" # install the python version needed

            - name: install python packages
              run: |
                  python -m pip install --upgrade pip
                  pip install -r base_requirements.txt
                  pip install -r us_requirements.txt

            - name: execute us_scrape_data.py script
              env:
                  NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
              run: python us_scrape_data.py -tt financials_annual -bs -1

            - name: Commit and Push Changes
              run: |
                  if [[ -n $(git status -s) ]]; then
                    git config user.name "GitHub Actions"
                    git config user.email "actions@users.noreply.github.com"
                    git add -A
                    git commit -m "Saving data to json due to error in idx_scrape_data.py"
                    git push
                  else
                    echo "No changes to commit."
                  fi
